package main

import (
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"sort"
	"strconv"
	"strings"
	"testing"
)

// TestCountLinesMatchesWcMinusL confirms physical-line counting is exactly the
// newline count `wc -l` reports, including the trailing-newline edge cases.
func TestCountLinesMatchesWcMinusL(t *testing.T) {
	cases := map[string]int{
		"trailing_newline.txt":    3,
		"no_trailing_newline.txt": 2,
		"empty.txt":               0,
	}
	for name, want := range cases {
		path := filepath.Join("testdata", "lines", name)
		src, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("read %s: %v", name, err)
		}
		if got := countLines(src); got != want {
			t.Errorf("countLines(%s) = %d, want %d", name, got, want)
		}
		if got := wcMinusL(t, path); got != want {
			t.Errorf("wc -l %s = %d, want %d (fixture drift)", name, got, want)
		}
	}
}

// wcMinusL shells out to `wc -l` so the fixtures are pinned to the reference
// tool the design points at; skips if wc is unavailable.
func wcMinusL(t *testing.T, path string) int {
	t.Helper()
	wc, err := exec.LookPath("wc")
	if err != nil {
		t.Skip("wc not available")
	}
	f, err := os.Open(path)
	if err != nil {
		t.Fatalf("open %s: %v", path, err)
	}
	defer f.Close()
	cmd := exec.Command(wc, "-l")
	cmd.Stdin = f
	out, err := cmd.Output()
	if err != nil {
		t.Fatalf("wc -l %s: %v", path, err)
	}
	n, err := strconv.Atoi(strings.TrimSpace(string(out)))
	if err != nil {
		t.Fatalf("parse wc output %q: %v", out, err)
	}
	return n
}

func TestIsGeneratedSource(t *testing.T) {
	cases := []struct {
		name string
		src  string
		want bool
	}{
		{"leading marker", "// Code generated by x. DO NOT EDIT.\n\npackage p\n", true},
		{"marker after build tag", "//go:build linux\n\n// Code generated foo\npackage p\n", true},
		{"no marker", "package p\n\nvar X = 1\n", false},
		{"marker after package ignored", "package p\n\n// Code generated later\n", false},
		{"empty", "", false},
	}
	for _, c := range cases {
		if got := isGeneratedSource([]byte(c.src)); got != c.want {
			t.Errorf("%s: isGeneratedSource = %v, want %v", c.name, got, c.want)
		}
	}
}

// TestScanFileGeneratedFixture checks generated-file detection and exemption
// against the on-disk fixtures, and that a generated file is skipped by
// scanFile (skip=true) while a plain file is scanned.
func TestScanFileGeneratedFixture(t *testing.T) {
	gen := filepath.Join("testdata", "generated", "generated.go")
	_, skip, err := scanFile(gen, "generated.go")
	if err != nil {
		t.Fatalf("scanFile generated: %v", err)
	}
	if !skip {
		t.Errorf("generated.go: want skip=true (exempt), got false")
	}

	plain := filepath.Join("testdata", "generated", "plain.go")
	fi, skip, err := scanFile(plain, "plain.go")
	if err != nil {
		t.Fatalf("scanFile plain: %v", err)
	}
	if skip {
		t.Errorf("plain.go: want skip=false, got true (marker after package must be ignored)")
	}
	if fi.Path != "plain.go" {
		t.Errorf("plain.go: Path = %q, want plain.go", fi.Path)
	}
}

// TestParseImportsHandlesAliasesDotsAndGroups confirms import extraction across
// aliased, dot, blank, single, and grouped-block import forms.
func TestParseImportsHandlesAliasesDotsAndGroups(t *testing.T) {
	path := filepath.Join("testdata", "imports", "mixed.go")
	src, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	got, err := parseImports("mixed.go", src)
	if err != nil {
		t.Fatalf("parseImports: %v", err)
	}
	sort.Strings(got)
	want := []string{"fmt", "go/ast", "go/parser", "go/token", "strings"}
	if !slices.Equal(got, want) {
		t.Errorf("parseImports = %v, want %v", got, want)
	}
}

func TestShouldSkipDir(t *testing.T) {
	skip := []string{"testdata", "vendor", "bin", ".git", ".rally", ".laps", ".hidden"}
	for _, name := range skip {
		if !shouldSkipDir(name) {
			t.Errorf("shouldSkipDir(%q) = false, want true", name)
		}
	}
	keep := []string{"internal", "cmd", "relay", "runner", "policy", ".", ".."}
	for _, name := range keep {
		if shouldSkipDir(name) {
			t.Errorf("shouldSkipDir(%q) = true, want false", name)
		}
	}
}

// TestScanRepoSkipsAndExempts walks the fixture tree and asserts that vendored,
// testdata, hidden, and generated files are excluded while ordinary sources —
// including nested ones — are kept with correct Package metadata.
func TestScanRepoSkipsAndExempts(t *testing.T) {
	root := filepath.Join("testdata", "tree")
	files, err := scanRepo(root)
	if err != nil {
		t.Fatalf("scanRepo: %v", err)
	}
	var paths []string
	pkgOf := map[string]string{}
	for _, f := range files {
		paths = append(paths, f.Path)
		pkgOf[f.Path] = f.Package
		if f.IsTest {
			t.Errorf("%s: IsTest = true, want false", f.Path)
		}
	}
	sort.Strings(paths)
	want := []string{"keep.go", "sub/nested.go"}
	if !slices.Equal(paths, want) {
		t.Errorf("scanRepo paths = %v, want %v", paths, want)
	}
	if pkgOf["keep.go"] != "." {
		t.Errorf("keep.go Package = %q, want .", pkgOf["keep.go"])
	}
	if pkgOf["sub/nested.go"] != "sub" {
		t.Errorf("sub/nested.go Package = %q, want sub", pkgOf["sub/nested.go"])
	}
}
