#!/usr/bin/env bash
# Regenerates internal/agent_prompt/managed_hashes.go — the set of SHA-256
# hashes (over the whitespace-trimmed body) of every canonical role instruction
# body rally has ever shipped via its embedded roles/<role>.md defaults.
#
# Used by agent_prompt.IsManagedRoleContent to decide, during the flat ->
# builtin/user role-folder migration, whether an on-disk role file is pristine
# rally content (safe to manage) or a user customization (preserve in user/).
#
# Run from the repo root: scripts/gen_managed_role_hashes.sh
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

out="internal/agent_prompt/managed_hashes.go"
roles_dir="internal/agent_prompt/roles"
existing_hashes="internal/agent_prompt/managed_hashes.go"

mapfile -t roles < <(
  {
    find "${roles_dir}" -maxdepth 1 -type f -name '*.md' -exec basename {} .md \;
    if [[ -f "${existing_hashes}" ]]; then
      python3 - "${existing_hashes}" <<'PY'
import re, sys
text = open(sys.argv[1], encoding="utf-8").read()
for role in re.findall(r'^\s*"([^"]+)":\s*\{', text, re.M):
    print(role)
PY
    fi
  } | sort -u
)

{
  echo "// Code generated by scripts/gen_managed_role_hashes.sh. DO NOT EDIT."
  echo "package agent_prompt"
  echo
  echo "// managedRoleContentHashes maps a role name to the SHA-256 hashes (hex, over"
  echo "// the whitespace-trimmed body) of every embedded role default rally has"
  echo "// shipped across releases. Regenerate with scripts/gen_managed_role_hashes.sh"
  echo "// after editing any roles/<role>.md."
  echo "var managedRoleContentHashes = map[string][]string{"
  for role in "${roles[@]}"; do
    path="${roles_dir}/${role}.md"
    # Collect distinct normalized hashes across all of git history plus the
    # current working-tree version of this role file. Existing generated hashes
    # are included so removed roles keep their append-only managed history.
    mapfile -t hashes < <(
      {
        if [[ -f "${existing_hashes}" ]]; then
          python3 - "${existing_hashes}" "${role}" <<'PY'
import re, sys
text = open(sys.argv[1], encoding="utf-8").read()
role = re.escape(sys.argv[2])
match = re.search(r'^\s*"' + role + r'":\s*\{(?P<body>.*?)^\s*\},', text, re.M | re.S)
if match:
    for h in re.findall(r'"([0-9a-f]{64})"', match.group("body")):
        sys.stdout.write(h + "\0")
PY
        fi
        for rev in $(git log --all --format='%H' -- "${path}"); do
          git cat-file -p "${rev}:${path}" 2>/dev/null || true
          printf '\0'
        done
        if [[ -f "${path}" ]]; then
          cat "${path}"
          printf '\0'
        fi
      } | python3 -c '
import sys, hashlib
data = sys.stdin.buffer.read().split(b"\0")
seen = []
for blob in data:
    if not blob.strip():
        continue
    text = blob.decode("utf-8", "replace").strip()
    if len(text) == 64 and all(c in "0123456789abcdef" for c in text):
        h = text
    else:
        h = hashlib.sha256(text.encode()).hexdigest()
    if h not in seen:
        seen.append(h)
for h in seen:
    print(h)
'
    )
    echo "	\"${role}\": {"
    for h in "${hashes[@]}"; do
      echo "		\"${h}\","
    done
    echo "	},"
  done
  echo "}"
} >"${out}"

gofmt -w "${out}"
echo "wrote ${out}"
