// Code generated by scripts/gen_managed_role_hashes.sh. DO NOT EDIT.
package agent_prompt

// managedRoleContentHashes maps a role name to the SHA-256 hashes (hex, over
// the whitespace-trimmed body) of every embedded role default rally has
// shipped across releases. Regenerate with scripts/gen_managed_role_hashes.sh
// after editing any roles/<role>.md.
var managedRoleContentHashes = map[string][]string{
	"junior": {
		"201b6962f8692bf852b31b3087be8f6149b02bd2d8793bd2e73f4c305b45d87d",
		"7ab113ebe91800f2181884f7245fabaf0a8da05ae3a20111d6243a21054e8817",
	},
	"recovery": {
		"e58368c743d147b37f1ed2033f281bd2e34cf2bcf32e9c75fe59182e13c33f96",
	},
	"senior": {
		"fe6c2d2399a245d68942f02ab6b72b5cdade101685079018ebd4d08d8bddf436",
		"b2ce959bcca640e789144d08f4ff7bbc608066a81d2a5b0f3db67d3f80d6d99d",
	},
	"ui": {
		"bed49d829d4434c78948e318f6d2813e14fd8763014e5f2a83baffeb84505044",
		"6731b673cde21547b112620f96f15cdc607aee93903d79eebc517074cd088ec8",
	},
	"verify": {
		"fb5d2e807c1b85b4ded1a776e24cd22ca012f1aa8dd1b1e54c2908f73bfa8c7b",
	},
}
